### ISSUE TITLE
would you consider adding a js engine?

### ISSUE THREAD

**Issue by amir-arad** [daid/SeriousProton2#5]
[QuickJS](https://bellard.org/quickjs/) or even [duktape](https://duktape.org/). 

the JS ecosystem is much more approachable for new modders

**Comment by daid** [comment]
- There are about 1200 lines of quite complex code dedicated to the lua script integration. Maintaining twice that I wouldn't like.
- Compared to SP1/EE1, the new lua SP2 implementation has a few really cool things. Including co-routine support (yielding and resuming later), lazy binding for performance, multiple script environments that can exists. And recently, direct property binding.
- Lua is proven to be stable, reliable and safe.
- I have a unhealthy dislike for javascript.

I don't see how Lua is really a blocker for modding. It certainly didn't hold back World of Warcraft (7000 addons) or Factorio (2000 mods available). Adding javascript is actually much more annoying for people, because there are different major versions, people will be confused that their normal set of libraries don't work, and expected functions don't exist.


I think the main issues with EE1 moddings support are:

- Parts of the API are chunky to use, especially for scenarios.
- Lack of examples.
- Certain bits of data is defined in "global" script files, and cannot be changed from scenarios.
